/** Countries with no commercial passenger airport. */
export const COUNTRIES_WITHOUT_AIRPORT = new Set([
  "AD", // Andorra
  "AQ", // Antarctica
  "BV", // Bouvet Island
  "GS", // South Georgia
  "HM", // Heard Island and McDonald Islands
  "IO", // British Indian Ocean Territory
  "LI", // Liechtenstein
  "MC", // Monaco
  "PN", // Pitcairn Islands
  "PS", // Palestine
  "SM", // San Marino
  "TF", // French Southern and Antarctic Lands
  "TK", // Tokelau
  "VA", // Vatican City
]);

/** How visitors typically reach countries with no commercial airport. */
export const COUNTRY_TRAVEL_ACCESS: Record<
  string,
  { mode: string; from: string }
> = {
  AD: { mode: "Road", from: "France · Spain" },
  AQ: { mode: "Expedition ship or flight", from: "Chile · Argentina · Australia · New Zealand" },
  BV: { mode: "Research vessel", from: "Norway" },
  GS: { mode: "Expedition ship", from: "Falkland Islands · Argentina" },
  HM: { mode: "Expedition ship", from: "Australia" },
  IO: { mode: "Military charter", from: "United Kingdom" },
  LI: { mode: "Road or rail", from: "Switzerland · Austria" },
  MC: { mode: "Road or rail", from: "France" },
  PN: { mode: "Passenger ship", from: "French Polynesia · New Zealand" },
  PS: { mode: "Road", from: "Israel · Jordan" },
  SM: { mode: "Road", from: "Italy" },
  TF: { mode: "Supply ship", from: "Réunion · Mauritius" },
  TK: { mode: "Passenger ship", from: "Samoa" },
  VA: { mode: "Road or walk", from: "Italy" },
};

export function getCountryTravelAccess(
  code: string,
): { mode: string; from: string } | undefined {
  return COUNTRY_TRAVEL_ACCESS[code];
}

/** Gateway airports that serve a territory but sit under another ISO code in OurAirports. */
export const MANUAL_COUNTRY_AIRPORTS: Record<string, string> = {
  AX: "MHQ", // Mariehamn serves Åland
  SJ: "LYR", // Longyearbyen serves Svalbard
};

/** Busiest airport IATA per US state (in-state, by passenger traffic). */
export const STATE_AIRPORTS: Record<string, string> = {
  AL: "BHM",
  AK: "ANC",
  AZ: "PHX",
  AR: "LIT",
  CA: "LAX",
  CO: "DEN",
  CT: "BDL",
  DE: "ILG",
  FL: "MCO",
  GA: "ATL",
  HI: "HNL",
  ID: "BOI",
  IL: "ORD",
  IN: "IND",
  IA: "DSM",
  KS: "ICT",
  KY: "CVG",
  LA: "MSY",
  ME: "PWM",
  MD: "BWI",
  MA: "BOS",
  MI: "DTW",
  MN: "MSP",
  MS: "JAN",
  MO: "STL",
  MT: "BZN",
  NE: "OMA",
  NV: "LAS",
  NH: "MHT",
  NJ: "EWR",
  NM: "ABQ",
  NY: "JFK",
  NC: "CLT",
  ND: "FAR",
  OH: "CLE",
  OK: "OKC",
  OR: "PDX",
  PA: "PHL",
  RI: "PVD",
  SC: "CHS",
  SD: "FSD",
  TN: "BNA",
  TX: "DFW",
  UT: "SLC",
  VT: "BTV",
  VA: "IAD",
  WA: "SEA",
  WV: "CRW",
  WI: "MKE",
  WY: "JAC",
};

/** Priority-ordered IATA codes per ISO2 — first match with scheduled service wins. */
export const COUNTRY_AIRPORT_PRIORITY: Record<string, string[]> = {
  AF: ["KBL"],
  AL: ["TIA"],
  DZ: ["ALG"],
  AS: ["PPG"],
  AO: ["LAD"],
  AI: ["AXA"],
  AG: ["ANU"],
  AR: ["EZE", "AEP", "COR"],
  AM: ["EVN"],
  AW: ["AUA"],
  AU: ["SYD", "MEL", "BNE", "PER"],
  AT: ["VIE", "SZG"],
  AZ: ["GYD", "BAK"],
  BS: ["NAS", "FPO"],
  BH: ["BAH"],
  BD: ["DAC", "CGP"],
  BB: ["BGI"],
  BY: ["MSQ"],
  BE: ["BRU", "CRL"],
  BZ: ["BZE"],
  BJ: ["COO"],
  BM: ["BDA"],
  BT: ["PBH", "PAR"],
  BO: ["VVI", "LPB", "CBB"],
  BA: ["SJJ"],
  BW: ["GBE"],
  BR: ["GRU", "GIG", "BSB", "CNF", "SSA"],
  VG: ["EIS", "VIJ"],
  BN: ["BWN"],
  BG: ["SOF", "VAR"],
  BF: ["OUA"],
  BI: ["BJM"],
  KH: ["PNH", "REP"],
  CM: ["NSI", "DLA"],
  CA: ["YYZ", "YVR", "YUL", "YYC"],
  CV: ["SID", "RAI"],
  BQ: ["BON", "EUX", "CUR"],
  KY: ["GCM", "CYB"],
  CF: ["BGF"],
  TD: ["NDJ"],
  CL: ["SCL", "IQQ"],
  CN: ["CAN", "PEK", "PKX", "PVG", "SHA", "CTU", "SZX"],
  CX: ["XCH"],
  CC: ["CCK"],
  CO: ["BOG", "MDE", "CLO"],
  KM: ["HAH", "YVA"],
  CG: ["BZV", "PNR"],
  CK: ["RAR", "AIT"],
  CR: ["SJO", "LIR"],
  HR: ["ZAG", "SPU"],
  CU: ["HAV", "VRA", "SCU"],
  CW: ["CUR"],
  CY: ["LCA", "PFO"],
  CZ: ["PRG", "BRQ"],
  DK: ["CPH", "BLL"],
  DJ: ["JIB"],
  DM: ["DOM", "DCF"],
  DO: ["SDQ", "PUJ", "STI"],
  CD: ["FIH", "FBM"],
  EC: ["UIO", "GYE"],
  EG: ["CAI", "HRG", "SSH"],
  SV: ["SAL"],
  GQ: ["SSG"],
  ER: ["ASM"],
  EE: ["TLL"],
  SZ: ["SHO", "MQP"],
  ET: ["ADD"],
  FK: ["MPN", "PSY"],
  FO: ["FAE"],
  FJ: ["NAN", "SUV"],
  FI: ["HEL", "OUL"],
  FR: ["CDG", "ORY", "NCE", "LYS", "MRS", "TLS", "BOD"],
  GF: ["CAY", "PAP"],
  PF: ["PPT", "BOB"],
  GA: ["LBV", "POG"],
  GM: ["BJL"],
  GE: ["TBS", "KUT"],
  DE: ["FRA", "MUC", "BER", "DUS", "HAM"],
  GH: ["ACC", "KMS"],
  GI: ["GIB"],
  GR: ["ATH", "SKG", "HER"],
  GL: ["GOH", "SFJ"],
  GD: ["GND"],
  GP: ["PTP"],
  GU: ["GUM"],
  GT: ["GUA", "FRS"],
  GG: ["GCI"],
  GN: ["CKY"],
  GW: ["OXB", "BQE"],
  GY: ["GEO", "OGM"],
  HT: ["PAP", "CAP"],
  HN: ["SAP", "TGU", "RTB"],
  HK: ["HKG"],
  HU: ["BUD", "DEB"],
  IS: ["KEF", "RKV"],
  IN: ["DEL", "BOM", "BLR", "MAA", "HYD", "CCU"],
  ID: ["CGK", "DPS", "SUB", "KNO"],
  IR: ["IKA", "THR", "MHD", "SYZ"],
  IQ: ["BGW", "EBL", "BSR"],
  IE: ["DUB", "SNN", "ORK"],
  IM: ["IOM"],
  IL: ["TLV", "ETM"],
  IT: ["FCO", "MXP", "LIN", "VCE", "NAP", "BGY"],
  CI: ["ABJ", "BOU"],
  JM: ["MBJ", "KIN"],
  JP: ["HND", "NRT", "KIX", "CTS", "FUK"],
  JE: ["JER"],
  JO: ["AMM", "AQJ"],
  KZ: ["ALA", "NQZ", "TSE"],
  KE: ["NBO", "MBA"],
  KI: ["TRW", "CXI"],
  XK: ["PRN"],
  KW: ["KWI"],
  KG: ["FRU", "OSS"],
  LA: ["VTE", "LPQ"],
  LV: ["RIX"],
  LB: ["BEY"],
  LS: ["MSU"],
  LR: ["ROB", "MLW"],
  LY: ["MJI", "BEN", "TIP"],
  LT: ["VNO", "KUN"],
  LU: ["LUX"],
  MO: ["MFM"],
  MG: ["TNR", "NOS"],
  MW: ["LLW", "BLZ"],
  MY: ["KUL", "PEN", "BKI"],
  MV: ["MLE", "GAN"],
  ML: ["BKO"],
  MT: ["MLA"],
  MH: ["MAJ", "KWA"],
  MQ: ["FDF"],
  MR: ["NKC", "NDB"],
  MU: ["MRU"],
  YT: ["DZA", "RUN"],
  MX: ["MEX", "CUN", "GDL", "MTY", "TIJ"],
  FM: ["PNI", "TKK", "YAP"],
  MD: ["RMO", "KIV"],
  MN: ["UBN", "ULN"],
  ME: ["TGD", "TIV"],
  MS: ["MNI"],
  MA: ["CMN", "RAK", "AGA"],
  MZ: ["MPM", "BEW"],
  MM: ["RGN", "MDL"],
  NA: ["WDH", "LUD"],
  NR: ["INU"],
  NP: ["KTM", "PKR"],
  NL: ["AMS", "EIN", "RTM"],
  NC: ["NOU"],
  NZ: ["AKL", "WLG", "CHC"],
  NI: ["MGA"],
  NE: ["NIM"],
  NG: ["LOS", "ABV", "KAN", "PHC"],
  NU: ["IUE"],
  NF: ["NLK"],
  KP: ["FNJ", "WOS"],
  MK: ["SKP", "OHD"],
  MP: ["SPN", "ROP", "TIQ"],
  NO: ["OSL", "BGO", "TRD", "SVG"],
  OM: ["MCT", "SLL"],
  PK: ["KHI", "LHE", "ISB"],
  PW: ["ROR"],
  PA: ["PTY", "DAV"],
  PG: ["POM", "LAE"],
  PY: ["ASU", "AGT"],
  PE: ["LIM", "CUZ", "AQP"],
  PH: ["MNL", "CEB", "CRK", "DVO"],
  PL: ["WAW", "KRK", "GDN"],
  PT: ["LIS", "OPO", "FAO"],
  PR: ["SJU", "BQN", "PSE"],
  QA: ["DOH"],
  RE: ["RUN", "ZSE"],
  RO: ["OTP", "CLJ", "TSR"],
  RU: ["SVO", "DME", "VKO", "LED", "KRR", "OVB"],
  RW: ["KGL"],
  BL: ["SBH"],
  SH: ["ASI", "HLE"],
  KN: ["SKB", "NEV"],
  LC: ["UVF", "SLU"],
  MF: ["SXM"],
  PM: ["FSP"],
  VC: ["SVD", "UNI"],
  WS: ["APW"],
  ST: ["TMS"],
  SA: ["JED", "RUH", "DMM", "MED"],
  SN: ["DSS", "DKR"],
  RS: ["BEG", "INI"],
  SC: ["SEZ", "PRI"],
  SL: ["FNA", "HGS"],
  SG: ["SIN"],
  SX: ["SXM"],
  SK: ["BTS", "KSC"],
  SI: ["LJU", "MBX"],
  SB: ["HIR", "GIZ"],
  SO: ["MGQ", "HGA"],
  ZA: ["JNB", "CPT", "DUR"],
  KR: ["ICN", "GMP", "PUS", "CJU"],
  SS: ["JUB"],
  ES: ["MAD", "BCN", "PMI", "AGP", "LPA"],
  LK: ["CMB", "HRI"],
  SD: ["KRT", "PZU"],
  SR: ["PBM", "ORG"],
  SE: ["ARN", "GOT", "MMX"],
  CH: ["ZRH", "GVA", "BSL"],
  SY: ["DAM", "ALP"],
  TW: ["TPE", "KHH", "RMQ"],
  TJ: ["DYU", "LBD"],
  TZ: ["DAR", "JRO", "ZNZ"],
  TH: ["BKK", "DMK", "CNX", "HKT"],
  TL: ["DIL"],
  TG: ["LFW"],
  TO: ["TBU", "HPA"],
  TT: ["POS", "TAB"],
  TN: ["TUN", "DJE", "SFA"],
  TR: ["IST", "SAW", "ESB", "AYT", "ADB"],
  TM: ["ASB", "CRZ"],
  TC: ["PLS", "GDT"],
  TV: ["FUN", "NFO"],
  UG: ["EBB"],
  UA: ["KBP", "ODS", "LWO", "HRK"],
  AE: ["DXB", "AUH", "SHJ"],
  GB: ["LHR", "LGW", "MAN", "STN", "EDI"],
  US: ["ATL", "LAX", "ORD", "DFW", "DEN", "JFK", "SFO", "SEA", "MIA", "EWR", "LAS", "MCO", "PHX", "IAH", "BOS"],
  UM: ["AWK", "MDY"],
  VI: ["STT", "STX"],
  UY: ["MVD", "PDP"],
  UZ: ["TAS", "SKD", "NMA"],
  VU: ["VLI", "SON"],
  VE: ["CCS", "MAR", "VLN"],
  VN: ["SGN", "HAN", "DAD", "CXR"],
  WF: ["WLS", "FUT"],
  EH: ["VIL", "EUN"],
  YE: ["SAH", "ADE", "GXF"],
  ZM: ["LUN", "NLA"],
  ZW: ["HRE", "VFA", "BUQ"],
};
