/**
 * Primary commercial airport IATA codes for library detail chips.
 * Countries: busiest gateway airport with scheduled passenger service.
 * States: busiest airport located in the state.
 *
 * Regenerate with: tsx scripts/generate-airport-data-module.ts > scripts/airport-data.ts
 */
export const COUNTRIES_WITHOUT_AIRPORT = new Set<string>([
  "AD",
  "AQ",
  "BV",
  "GS",
  "HM",
  "IO",
  "LI",
  "MC",
  "PN",
  "PS",
  "SM",
  "TF",
  "TK",
  "VA",
]);

export const COUNTRY_AIRPORTS: Record<string, string> = {
  AE: "DXB",
  AF: "KBL",
  AG: "ANU",
  AI: "AXA",
  AL: "TIA",
  AM: "EVN",
  AO: "LAD",
  AR: "EZE",
  AS: "PPG",
  AT: "VIE",
  AU: "SYD",
  AW: "AUA",
  AX: "MHQ",
  AZ: "GYD",
  BA: "SJJ",
  BB: "BGI",
  BD: "DAC",
  BE: "BRU",
  BF: "OUA",
  BG: "SOF",
  BH: "BAH",
  BI: "BJM",
  BJ: "COO",
  BL: "SBH",
  BM: "BDA",
  BN: "BWN",
  BO: "VVI",
  BQ: "BON",
  BR: "GRU",
  BS: "NAS",
  BT: "PBH",
  BW: "GBE",
  BY: "MSQ",
  BZ: "BZE",
  CA: "YYZ",
  CC: "CCK",
  CD: "FIH",
  CF: "BGF",
  CG: "BZV",
  CH: "ZRH",
  CI: "ABJ",
  CK: "RAR",
  CL: "SCL",
  CM: "NSI",
  CN: "CAN",
  CO: "BOG",
  CR: "SJO",
  CU: "HAV",
  CV: "SID",
  CW: "CUR",
  CX: "XCH",
  CY: "LCA",
  CZ: "PRG",
  DE: "FRA",
  DJ: "JIB",
  DK: "CPH",
  DM: "DOM",
  DO: "SDQ",
  DZ: "ALG",
  EC: "UIO",
  EE: "TLL",
  EG: "CAI",
  EH: "VIL",
  ER: "ASM",
  ES: "MAD",
  ET: "ADD",
  FI: "HEL",
  FJ: "NAN",
  FK: "MPN",
  FM: "PNI",
  FO: "FAE",
  FR: "CDG",
  GA: "LBV",
  GB: "LHR",
  GD: "GND",
  GE: "TBS",
  GF: "CAY",
  GG: "GCI",
  GH: "ACC",
  GI: "GIB",
  GL: "GOH",
  GM: "BJL",
  GN: "CKY",
  GP: "PTP",
  GQ: "SSG",
  GR: "ATH",
  GT: "GUA",
  GU: "GUM",
  GW: "OXB",
  GY: "GEO",
  HK: "HKG",
  HN: "SAP",
  HR: "ZAG",
  HT: "PAP",
  HU: "BUD",
  ID: "CGK",
  IE: "DUB",
  IL: "TLV",
  IM: "IOM",
  IN: "DEL",
  IQ: "BGW",
  IR: "IKA",
  IS: "KEF",
  IT: "FCO",
  JE: "JER",
  JM: "MBJ",
  JO: "AMM",
  JP: "HND",
  KE: "NBO",
  KG: "OSS",
  KH: "DSY",
  KI: "TRW",
  KM: "HAH",
  KN: "SKB",
  KP: "FNJ",
  KR: "ICN",
  KW: "KWI",
  KY: "GCM",
  KZ: "ALA",
  LA: "VTE",
  LB: "BEY",
  LC: "UVF",
  LK: "CMB",
  LR: "ROB",
  LS: "MSU",
  LT: "VNO",
  LU: "LUX",
  LV: "RIX",
  LY: "MJI",
  MA: "CMN",
  MD: "RMO",
  ME: "TGD",
  MF: "SFG",
  MG: "TNR",
  MH: "MAJ",
  MK: "SKP",
  ML: "BKO",
  MM: "RGN",
  MN: "UBN",
  MO: "MFM",
  MP: "SPN",
  MQ: "FDF",
  MR: "NKC",
  MS: "MNI",
  MT: "MLA",
  MU: "MRU",
  MV: "MLE",
  MW: "LLW",
  MX: "MEX",
  MY: "KUL",
  MZ: "MPM",
  NA: "WDH",
  NC: "NOU",
  NE: "NIM",
  NF: "NLK",
  NG: "LOS",
  NI: "MGA",
  NL: "AMS",
  NO: "OSL",
  NP: "KTM",
  NR: "INU",
  NU: "IUE",
  NZ: "AKL",
  OM: "MCT",
  PA: "PTY",
  PE: "LIM",
  PF: "PPT",
  PG: "POM",
  PH: "MNL",
  PK: "KHI",
  PL: "WAW",
  PM: "FSP",
  PR: "SJU",
  PT: "LIS",
  PW: "ROR",
  PY: "ASU",
  QA: "DOH",
  RE: "RUN",
  RO: "OTP",
  RS: "BEG",
  RU: "SVO",
  RW: "KGL",
  SA: "JED",
  SB: "HIR",
  SC: "SEZ",
  SD: "KRT",
  SE: "ARN",
  SG: "SIN",
  SH: "ASI",
  SI: "LJU",
  SJ: "LYR",
  SK: "BTS",
  SL: "FNA",
  SN: "DSS",
  SO: "MGQ",
  SR: "PBM",
  SS: "JUB",
  ST: "TMS",
  SV: "SAL",
  SX: "SXM",
  SY: "DAM",
  SZ: "SHO",
  TC: "PLS",
  TD: "NDJ",
  TG: "LFW",
  TH: "BKK",
  TJ: "DYU",
  TL: "DIL",
  TM: "ASB",
  TN: "TUN",
  TO: "TBU",
  TR: "IST",
  TT: "POS",
  TV: "FUN",
  TW: "TPE",
  TZ: "DAR",
  UA: "LWO",
  UG: "EBB",
  UM: "AWK",
  US: "ATL",
  UY: "MVD",
  UZ: "TAS",
  VC: "SVD",
  VE: "CCS",
  VG: "EIS",
  VI: "STT",
  VN: "SGN",
  VU: "VLI",
  WF: "WLS",
  WS: "APW",
  XK: "PRN",
  YE: "SAH",
  YT: "DZA",
  ZA: "JNB",
  ZM: "LUN",
  ZW: "HRE",
};

export const STATE_AIRPORTS: Record<string, string> = {
  AK: "ANC",
  AL: "BHM",
  AR: "LIT",
  AZ: "PHX",
  CA: "LAX",
  CO: "DEN",
  CT: "BDL",
  DE: "ILG",
  FL: "MCO",
  GA: "ATL",
  HI: "HNL",
  IA: "DSM",
  ID: "BOI",
  IL: "ORD",
  IN: "IND",
  KS: "ICT",
  KY: "CVG",
  LA: "MSY",
  MA: "BOS",
  MD: "BWI",
  ME: "PWM",
  MI: "DTW",
  MN: "MSP",
  MO: "STL",
  MS: "JAN",
  MT: "BZN",
  NC: "CLT",
  ND: "FAR",
  NE: "OMA",
  NH: "MHT",
  NJ: "EWR",
  NM: "ABQ",
  NV: "LAS",
  NY: "JFK",
  OH: "CLE",
  OK: "OKC",
  OR: "PDX",
  PA: "PHL",
  RI: "PVD",
  SC: "CHS",
  SD: "FSD",
  TN: "BNA",
  TX: "DFW",
  UT: "SLC",
  VA: "IAD",
  VT: "BTV",
  WA: "SEA",
  WI: "MKE",
  WV: "CRW",
  WY: "JAC",
};

export function getCountryAirport(code: string): string | undefined {
  if (COUNTRIES_WITHOUT_AIRPORT.has(code)) return undefined;
  return COUNTRY_AIRPORTS[code];
}

export function getStateAirport(postal: string): string | undefined {
  return STATE_AIRPORTS[postal.toUpperCase()];
}

export { COUNTRY_TRAVEL_ACCESS, getCountryTravelAccess } from "./airport-data-sources";

