/**
 * Official bird and plant/flower emblems for library detail chips.
 * US states: Wikipedia "List of U.S. state birds" / "List of U.S. state and territory flowers".
 * Countries: Wikipedia "List of national birds" / "List of national flowers" (sparse; many places have no official emblem).
 */

export type PlaceEmblems = {
  bird?: string;
  plant?: string;
};

export const STATE_BIRDS: Record<string, string> = {
  AK: "Willow ptarmigan",
  AL: "Yellowhammer",
  AR: "Northern mockingbird",
  AZ: "Cactus wren",
  CA: "California quail",
  CO: "Lark bunting",
  CT: "American robin",
  DE: "Blue Hen chicken",
  FL: "Northern mockingbird",
  GA: "Brown thrasher",
  HI: "Nene",
  IA: "American goldfinch",
  ID: "Mountain bluebird",
  IL: "Northern cardinal",
  IN: "Northern cardinal",
  KS: "Western meadowlark",
  KY: "Northern cardinal",
  LA: "Brown pelican",
  MA: "Black-capped chickadee",
  MD: "Baltimore oriole",
  ME: "Chickadee",
  MI: "American robin",
  MN: "Common loon",
  MO: "Eastern bluebird",
  MS: "Northern mockingbird",
  MT: "Western meadowlark",
  NC: "Northern cardinal",
  ND: "Western meadowlark",
  NE: "Western meadowlark",
  NH: "Purple finch",
  NJ: "American goldfinch",
  NM: "Greater roadrunner",
  NV: "Mountain bluebird",
  NY: "Eastern bluebird",
  OH: "Northern cardinal",
  OK: "Scissor-tailed flycatcher",
  OR: "Western meadowlark",
  PA: "Ruffed grouse",
  RI: "Rhode Island Red",
  SC: "Carolina wren",
  SD: "Ring-necked pheasant",
  TN: "Northern mockingbird",
  TX: "Northern mockingbird",
  UT: "California gull",
  VA: "Northern cardinal",
  VT: "Hermit thrush",
  WA: "Willow goldfinch",
  WI: "American robin",
  WV: "Northern cardinal",
  WY: "Western meadowlark",
};

export const STATE_PLANTS: Record<string, string> = {
  AK: "Forget-me-not",
  AL: "Camellia",
  AR: "Apple blossom",
  AZ: "Saguaro blossom",
  CA: "California poppy",
  CO: "Rocky Mountain columbine",
  CT: "Mountain laurel",
  DE: "Peach blossom",
  FL: "Orange blossom",
  GA: "Cherokee rose",
  HI: "Yellow hibiscus",
  IA: "Wild rose",
  ID: "Syringa",
  IL: "Violet",
  IN: "Peony",
  KS: "Sunflower",
  KY: "Goldenrod",
  LA: "Magnolia",
  MA: "Mayflower",
  MD: "Black-eyed Susan",
  ME: "White pine cone and tassel",
  MI: "Apple blossom",
  MN: "Pink and white lady's slipper",
  MO: "Hawthorn",
  MS: "Magnolia",
  MT: "Bitterroot",
  NC: "Flowering dogwood",
  ND: "Wild prairie rose",
  NE: "Goldenrod",
  NH: "Purple lilac",
  NJ: "Violet",
  NM: "Yucca flower",
  NV: "Sagebrush",
  NY: "Rose",
  OH: "Scarlet carnation",
  OK: "Oklahoma rose",
  OR: "Oregon grape",
  PA: "Mountain laurel",
  RI: "Violet",
  SC: "Yellow jessamine",
  SD: "Pasque flower",
  TN: "Iris",
  TX: "Bluebonnet",
  UT: "Sego lily",
  VA: "American dogwood",
  VT: "Red clover",
  WA: "Coast rhododendron",
  WI: "Wood violet",
  WV: "Rhododendron",
  WY: "Indian paintbrush",
};

export const COUNTRY_BIRDS: Record<string, string> = {
  AE: "Saker falcon",
  AF: "Golden eagle",
  AG: "Magnificent frigatebird",
  AI: "Zenaida dove",
  AL: "Golden eagle",
  AM: "Golden eagle",
  AO: "Red-crested turaco",
  AR: "Rufous hornero",
  AT: "Barn swallow",
  AU: "Emu",
  AW: "Brown-throated parakeet",
  AZ: "Golden eagle",
  BA: "Golden eagle",
  BB: "Pelican",
  BD: "Oriental magpie-robin",
  BE: "Common kestrel",
  BG: "Golden eagle",
  BH: "White-eared bulbul",
  BI: "Southern ground hornbill",
  BM: "Bermuda petrel",
  BN: "White-bellied sea eagle",
  BO: "Andean condor",
  BR: "Rufous-bellied thrush",
  BS: "American flamingo",
  BT: "Common raven",
  BW: "Kori bustard",
  BY: "White stork",
  BZ: "Keel-billed toucan",
  CD: "Congo peacock",
  CF: "Grey parrot",
  CG: "Grey parrot",
  CH: "Barn swallow",
  CI: "White-cheeked oliveback",
  CL: "Andean condor",
  CM: "Grey parrot",
  CN: "Red-crowned crane",
  CO: "Andean condor",
  CR: "Clay-colored thrush",
  CU: "Cuban trogon",
  CY: "Cyprus warbler",
  CZ: "Eagle",
  DK: "Mute swan",
  DM: "Imperial amazon",
  DO: "Hispaniolan trogon",
  DZ: "Barbary partridge",
  EC: "Andean condor",
  EE: "Barn swallow",
  EG: "Steppe eagle",
  ER: "White-cheeked turaco",
  ES: "Spanish imperial eagle",
  ET: "Wattled ibis",
  FI: "Whooper swan",
  FJ: "Collared lory",
  FM: "Caroline Islands ground dove",
  FO: "Eurasian oystercatcher",
  FR: "Gallic rooster",
  GA: "Grey parrot",
  GB: "European robin",
  GD: "Grenada dove",
  GE: "Common pheasant",
  GH: "Tawny eagle",
  GI: "Barbary partridge",
  GT: "Resplendent quetzal",
  GY: "Hoatzin",
  HK: "Black kite",
  HN: "Scarlet macaw",
  HR: "Common nightingale",
  HT: "Hispaniolan trogon",
  HU: "Great bustard",
  ID: "Javan hawk-eagle",
  IE: "Northern lapwing",
  IL: "Hoopoe",
  IN: "Indian peafowl",
  IQ: "Chukar partridge",
  IR: "Common nightingale",
  IS: "Gyrfalcon",
  IT: "Italian sparrow",
  JM: "Doctor bird",
  JO: "Sinai rosefinch",
  JP: "Green pheasant",
  KE: "Lilac-breasted roller",
  KG: "Golden eagle",
  KH: "Giant ibis",
  KI: "Great frigatebird",
  KN: "Brown pelican",
  KP: "Northern goshawk",
  KR: "Korean magpie",
  KY: "Grand Cayman parrot",
  KZ: "Golden eagle",
  LA: "Siamese fireback",
  LC: "Saint Lucia amazon",
  LI: "Eagle",
  LK: "Sri Lanka junglefowl",
  LR: "Common bulbul",
  LS: "Southern bald ibis",
  LT: "White stork",
  LU: "Goldcrest",
  LV: "White wagtail",
  LY: "Eagle",
  MA: "Menetries's warbler",
  MD: "Golden eagle",
  ME: "Golden eagle",
  MG: "Madagascar fish eagle",
  MH: "Frigatebird",
  MK: "Golden eagle",
  ML: "Golden eagle",
  MM: "Green peafowl",
  MN: "Saker falcon",
  MS: "Montserrat oriole",
  MT: "Blue rock thrush",
  MU: "Mauritius kestrel",
  MV: "White-breasted waterhen",
  MW: "African fish eagle",
  MX: "Golden eagle",
  MY: "Rhinoceros hornbill",
  MZ: "African fish eagle",
  NA: "African fish eagle",
  NE: "Ostrich",
  NG: "Black crowned crane",
  NI: "Turquoise-browed motmot",
  NL: "Black-tailed godwit",
  NO: "White-throated dipper",
  NP: "Himalayan monal",
  NR: "Frigatebird",
  NZ: "Kiwi",
  PA: "Harpy eagle",
  PE: "Andean cock-of-the-rock",
  PG: "Raggiana bird-of-paradise",
  PH: "Philippine eagle",
  PK: "Chukar partridge",
  PL: "White-tailed eagle",
  PR: "Puerto Rican spindalis",
  PS: "Palestine sunbird",
  PT: "Barcelos rooster",
  PW: "Palau fruit dove",
  PY: "Bare-throated bellbird",
  RO: "Golden eagle",
  RS: "Eagle",
  RW: "Grey crowned crane",
  SB: "Eagle",
  SC: "Seychelles black parrot",
  SD: "Secretary bird",
  SE: "Common blackbird",
  SG: "Crimson sunbird",
  SI: "Barn swallow",
  SK: "Eagle",
  SN: "White stork",
  SR: "Scarlet macaw",
  SS: "Secretary bird",
  SV: "Turquoise-browed motmot",
  SZ: "Purple-crested turaco",
  TD: "Ostrich",
  TH: "Siamese fireback",
  TJ: "Golden eagle",
  TM: "Houbara bustard",
  TN: "Lanner falcon",
  TO: "Tongan whistler",
  TT: "Scarlet ibis",
  TV: "Pacific imperial pigeon",
  TW: "Mikado pheasant",
  TZ: "Lilac-breasted roller",
  UA: "Nightingale",
  UG: "Grey crowned crane",
  US: "Bald eagle",
  UY: "Southern lapwing",
  UZ: "Huma",
  VC: "St Vincent parrot",
  VE: "Venezuelan troupial",
  VG: "Mourning dove",
  VN: "Vietnamese pheasant",
  VU: "Buff-banded rail",
  WS: "Tooth-billed pigeon",
  XK: "Golden eagle",
  YE: "Arabian grosbeak",
  ZA: "Blue crane",
  ZM: "African fish eagle",
  ZW: "Zimbabwe bird",
};

export const COUNTRY_PLANTS: Record<string, string> = {
  AE: "Tribulus",
  AF: "Tulip",
  AL: "Red poppy",
  AM: "Corn poppy",
  AO: "Welwitschia",
  AR: "Ceibo",
  AT: "Edelweiss",
  AU: "Golden wattle",
  AZ: "Pomegranate flower",
  BA: "Lilac",
  BB: "Pride of Barbados",
  BD: "Water lily",
  BE: "Red poppy",
  BG: "Rose",
  BN: "Simpur",
  BO: "Kantuta",
  BR: "Ipê-amarelo",
  BT: "Blue poppy",
  BW: "Sedge",
  BY: "Flax",
  BZ: "Black orchid",
  CA: "Maple leaf",
  CD: "Torch ginger",
  CH: "Edelweiss",
  CL: "Copihue",
  CN: "Peony",
  CO: "Cattleya trianae",
  CR: "Guaria morada",
  CU: "White ginger lily",
  CY: "Cyclamen",
  CZ: "Rose",
  DE: "Cornflower",
  DK: "Marguerite daisy",
  DO: "Mahogany flower",
  DZ: "Iris",
  EC: "Chuquiraga",
  EE: "Cornflower",
  EG: "Lotus",
  ES: "Carnation",
  ET: "Calla lily",
  FI: "Lily of the valley",
  FJ: "Tagimaucia",
  FR: "Lily",
  GB: "Rose",
  GE: "Vine",
  GH: "Eagle claw",
  GR: "Laurel",
  GT: "White nun orchid",
  GY: "Victoria amazonica",
  HK: "Bauhinia",
  HN: "Rhyncholaelia digbyana",
  HR: "Iris",
  HT: "Hibiscus",
  HU: "Tulip",
  ID: "Melati",
  IE: "Shamrock",
  IL: "Anemone",
  IN: "Lotus",
  IQ: "Rose",
  IR: "Red rose",
  IS: "Mountain avens",
  IT: "Lily",
  JM: "Lignum vitae",
  JO: "Black iris",
  JP: "Cherry blossom",
  KE: "Orchid",
  KH: "Rumduol",
  KR: "Mugunghwa",
  KZ: "Lily",
  LA: "Dok champa",
  LB: "Cedar",
  LK: "Blue water lily",
  LS: "Spiral aloe",
  LT: "Rue",
  LU: "Rose",
  LV: "Oxeye daisy",
  LY: "Pomegranate blossom",
  MA: "Rose",
  ME: "Mimosa",
  MG: "Poinciana",
  MK: "Poppy",
  MM: "Padauk",
  MN: "Scabiosa",
  MO: "Lotus",
  MT: "Maltese rock-centaury",
  MU: "Trochetia boutoniana",
  MW: "Yellow orchid",
  MX: "Dahlia",
  MY: "Hibiscus",
  MZ: "Sycamore fig",
  NA: "Welwitschia",
  NG: "Costus spectabilis",
  NI: "Sacuanjoche",
  NL: "Tulip",
  NO: "Purple heather",
  NP: "Rhododendron",
  NZ: "Silver fern",
  PA: "Holy Ghost orchid",
  PE: "Cantuta",
  PG: "Sepik blue orchid",
  PH: "Sampaguita",
  PK: "Jasmine",
  PL: "Corn poppy",
  PT: "Lavender",
  PY: "Mburucuyá",
  RO: "Dog rose",
  RS: "Natal lily",
  RU: "Chamomile",
  SA: "Date palm",
  SB: "Hibiscus",
  SD: "Hibiscus",
  SE: "Linnaea",
  SG: "Vanda Miss Joaquim",
  SI: "Carnation",
  SK: "Rose",
  SN: "Baobab flower",
  SR: "Faya lobi",
  SV: "Flor de izote",
  SY: "Jasmine",
  SZ: "Erythrina",
  TH: "Cassia fistula",
  TN: "Jasmine",
  TO: "Heilala",
  TR: "Tulip",
  TT: "Chaconia",
  TW: "Plum blossom",
  TZ: "African violet",
  UA: "Sunflower",
  UG: "Frangipani",
  US: "Rose",
  UY: "Ceibo",
  UZ: "Cotton flower",
  VE: "Orchid",
  VN: "Lotus",
  VU: "Hibiscus",
  WS: "Red ginger",
  ZA: "King protea",
  ZM: "Bougainvillea",
  ZW: "Flame lily",
};

export function getStateEmblems(postal: string): PlaceEmblems | undefined {
  const bird = STATE_BIRDS[postal];
  const plant = STATE_PLANTS[postal];
  if (!bird && !plant) return undefined;
  return { ...(bird ? { bird } : {}), ...(plant ? { plant } : {}) };
}

export function getCountryEmblems(code: string): PlaceEmblems | undefined {
  const bird = COUNTRY_BIRDS[code];
  const plant = COUNTRY_PLANTS[code];
  if (!bird && !plant) return undefined;
  return { ...(bird ? { bird } : {}), ...(plant ? { plant } : {}) };
}
