/**
 * Dominant ecosystem / climate labels for library chips.
 * Kid-friendly single words or brief phrases; varied places use a short
 * "contains" list. Sourced from Köppen climate summaries and WWF ecoregions.
 */

export const COUNTRY_ECOSYSTEMS: Record<string, string> = {
  AD: "Alpine forest",
  AE: "Desert",
  AF: "Mountains & desert",
  AG: "Tropical islands",
  AI: "Tropical islands",
  AL: "Mediterranean hills",
  AM: "Mountains & steppe",
  AO: "Savanna & rainforest",
  AQ: "Ice sheet",
  AR: "Pampas, Andes & desert",
  AS: "Tropical islands",
  AT: "Alpine forest",
  AU: "Desert & grasslands",
  AW: "Dry tropical scrub",
  AX: "Boreal forest",
  AZ: "Mountains & steppe",
  BA: "Temperate forest",
  BB: "Tropical islands",
  BD: "River delta & monsoon",
  BE: "Temperate forest",
  BF: "Savanna",
  BG: "Temperate forest",
  BH: "Desert",
  BI: "Highland savanna",
  BJ: "Savanna",
  BL: "Tropical islands",
  BM: "Subtropical islands",
  BN: "Tropical rainforest",
  BO: "Andes, rainforest & desert",
  BQ: "Tropical islands",
  BR: "Rainforest & savanna",
  BS: "Tropical islands",
  BT: "Himalayan forests",
  BV: "Subantarctic islands",
  BW: "Savanna & desert",
  BY: "Temperate forest",
  BZ: "Tropical rainforest",
  CA: "Forests, plains & tundra",
  CC: "Tropical islands",
  CD: "Tropical rainforest",
  CF: "Savanna & rainforest",
  CG: "Tropical rainforest",
  CH: "Alpine forest",
  CI: "Rainforest & savanna",
  CK: "Tropical islands",
  CL: "Desert, Andes & forests",
  CM: "Rainforest & savanna",
  CN: "Mountains, plains & desert",
  CO: "Rainforest & Andes",
  CR: "Tropical rainforest",
  CU: "Tropical islands",
  CV: "Dry tropical islands",
  CW: "Dry tropical scrub",
  CX: "Tropical rainforest",
  CY: "Mediterranean scrub",
  CZ: "Temperate forest",
  DE: "Temperate forest",
  DJ: "Desert",
  DK: "Temperate farmland",
  DM: "Tropical rainforest",
  DO: "Tropical forest",
  DZ: "Desert",
  EC: "Rainforest & Andes",
  EE: "Boreal forest",
  EG: "Desert",
  EH: "Desert",
  ER: "Desert & highlands",
  ES: "Mediterranean scrub",
  ET: "Highlands & savanna",
  FI: "Boreal forest",
  FJ: "Tropical islands",
  FK: "Cold grasslands",
  FM: "Tropical islands",
  FO: "Tundra islands",
  FR: "Temperate forest",
  GA: "Tropical rainforest",
  GB: "Temperate forest",
  GD: "Tropical islands",
  GE: "Mountains & forest",
  GF: "Tropical rainforest",
  GG: "Temperate islands",
  GH: "Savanna & forest",
  GI: "Mediterranean scrub",
  GL: "Ice sheet & tundra",
  GM: "Savanna",
  GN: "Rainforest & savanna",
  GP: "Tropical islands",
  GQ: "Tropical rainforest",
  GR: "Mediterranean scrub",
  GS: "Subantarctic islands",
  GT: "Tropical forest",
  GU: "Tropical islands",
  GW: "Mangroves & savanna",
  GY: "Tropical rainforest",
  HK: "Subtropical hills",
  HM: "Subantarctic islands",
  HN: "Tropical forest",
  HR: "Mediterranean & forest",
  HT: "Tropical hills",
  HU: "Temperate plains",
  ID: "Tropical rainforest",
  IE: "Temperate grassland",
  IL: "Mediterranean scrub",
  IM: "Temperate islands",
  IN: "Monsoon forests & desert",
  IO: "Tropical islands",
  IQ: "Desert & steppe",
  IR: "Mountains & desert",
  IS: "Volcanic tundra",
  IT: "Mediterranean & Alps",
  JE: "Temperate islands",
  JM: "Tropical forest",
  JO: "Desert",
  JP: "Temperate forest",
  KE: "Savanna",
  KG: "Mountains & steppe",
  KH: "Tropical forest",
  KI: "Coral atolls",
  KM: "Tropical islands",
  KN: "Tropical islands",
  KP: "Temperate forest",
  KR: "Temperate forest",
  KW: "Desert",
  KY: "Tropical islands",
  KZ: "Steppe",
  LA: "Tropical forest",
  LB: "Mediterranean hills",
  LC: "Tropical islands",
  LI: "Alpine forest",
  LK: "Tropical forest",
  LR: "Tropical rainforest",
  LS: "Highland grassland",
  LT: "Temperate forest",
  LU: "Temperate forest",
  LV: "Temperate forest",
  LY: "Desert",
  MA: "Mountains & desert",
  MC: "Mediterranean coast",
  MD: "Temperate plains",
  ME: "Mountains & forest",
  MF: "Tropical islands",
  MG: "Rainforest & dry forest",
  MH: "Coral atolls",
  MK: "Mountains & forest",
  ML: "Desert & savanna",
  MM: "Tropical forest",
  MN: "Steppe & desert",
  MO: "Subtropical coast",
  MP: "Tropical islands",
  MQ: "Tropical islands",
  MR: "Desert",
  MS: "Tropical islands",
  MT: "Mediterranean scrub",
  MU: "Tropical islands",
  MV: "Coral atolls",
  MW: "Savanna",
  MX: "Deserts, forests & tropics",
  MY: "Tropical rainforest",
  MZ: "Savanna",
  NA: "Desert & savanna",
  NC: "Tropical forest",
  NE: "Desert & savanna",
  NF: "Subtropical islands",
  NG: "Savanna & rainforest",
  NI: "Tropical forest",
  NL: "Temperate farmland",
  NO: "Fjords & forest",
  NP: "Himalayan forests",
  NR: "Tropical islands",
  NU: "Tropical islands",
  NZ: "Temperate forest",
  OM: "Desert",
  PA: "Tropical rainforest",
  PE: "Andes, desert & rainforest",
  PF: "Tropical islands",
  PG: "Tropical rainforest",
  PH: "Tropical islands",
  PK: "Mountains, plains & desert",
  PL: "Temperate plains",
  PM: "Boreal islands",
  PN: "Subtropical islands",
  PR: "Tropical islands",
  PS: "Mediterranean scrub",
  PT: "Mediterranean scrub",
  PW: "Tropical islands",
  PY: "Grassland & forest",
  QA: "Desert",
  RE: "Tropical islands",
  RO: "Temperate forest",
  RS: "Temperate forest",
  RU: "Taiga & tundra",
  RW: "Highland forest",
  SA: "Desert",
  SB: "Tropical rainforest",
  SC: "Tropical islands",
  SD: "Desert & savanna",
  SE: "Boreal forest",
  SG: "Tropical city-state",
  SH: "Remote Atlantic islands",
  SI: "Alpine forest",
  SJ: "Arctic tundra",
  SK: "Temperate forest",
  SL: "Tropical rainforest",
  SM: "Mediterranean hills",
  SN: "Savanna",
  SO: "Desert & savanna",
  SR: "Tropical rainforest",
  SS: "Savanna",
  ST: "Tropical islands",
  SV: "Tropical forest",
  SX: "Tropical islands",
  SY: "Desert & steppe",
  SZ: "Highland savanna",
  TC: "Tropical islands",
  TD: "Desert & savanna",
  TF: "Subantarctic islands",
  TG: "Savanna",
  TH: "Tropical forest",
  TJ: "Mountains & desert",
  TK: "Coral atolls",
  TL: "Tropical forest",
  TM: "Desert",
  TN: "Mediterranean & desert",
  TO: "Tropical islands",
  TR: "Mountains & steppe",
  TT: "Tropical islands",
  TV: "Coral atolls",
  TW: "Subtropical forest",
  TZ: "Savanna",
  UA: "Temperate plains",
  UG: "Savanna",
  UM: "Tropical islands",
  US: "Deserts to forests",
  UY: "Grassland",
  UZ: "Desert & steppe",
  VA: "Mediterranean city",
  VC: "Tropical islands",
  VE: "Rainforest & savanna",
  VG: "Tropical islands",
  VI: "Tropical islands",
  VN: "Tropical forest",
  VU: "Tropical islands",
  WF: "Tropical islands",
  WS: "Tropical islands",
  XK: "Mountains & forest",
  YE: "Desert & mountains",
  YT: "Tropical islands",
  ZA: "Savanna & scrub",
  ZM: "Savanna",
  ZW: "Savanna",
};

export const STATE_ECOSYSTEMS: Record<string, string> = {
  AK: "Tundra & rainforest",
  AL: "Temperate forest",
  AR: "Temperate forest",
  AZ: "Desert",
  CA: "Coast, desert & mountains",
  CO: "Mountains & plains",
  CT: "Temperate forest",
  DE: "Coastal plains",
  FL: "Subtropical wetlands",
  GA: "Temperate forest",
  HI: "Tropical islands",
  IA: "Prairie",
  ID: "Mountains & desert",
  IL: "Prairie & forest",
  IN: "Temperate forest",
  KS: "Prairie",
  KY: "Temperate forest",
  LA: "Wetlands & forest",
  MA: "Temperate forest",
  MD: "Coastal plains",
  ME: "Boreal forest",
  MI: "Temperate forest",
  MN: "Prairie & forest",
  MO: "Prairie & forest",
  MS: "Temperate forest",
  MT: "Mountains & plains",
  NC: "Coast to mountains",
  ND: "Prairie",
  NE: "Prairie",
  NH: "Temperate forest",
  NJ: "Coastal plains",
  NM: "Desert & mountains",
  NV: "Desert",
  NY: "Temperate forest",
  OH: "Temperate forest",
  OK: "Prairie & forest",
  OR: "Temperate rainforest",
  PA: "Temperate forest",
  RI: "Coastal plains",
  SC: "Temperate forest",
  SD: "Prairie",
  TN: "Temperate forest",
  TX: "Plains, desert & coast",
  UT: "Desert & mountains",
  VA: "Coast to mountains",
  VT: "Temperate forest",
  WA: "Temperate rainforest",
  WI: "Temperate forest",
  WV: "Temperate forest",
  WY: "Mountains & plains",
};

export function getCountryEcosystem(code: string): string | undefined {
  return COUNTRY_ECOSYSTEMS[code];
}

export function getStateEcosystem(postal: string): string | undefined {
  return STATE_ECOSYSTEMS[postal];
}
