/** Curated trivia for library detail pages — one remarkable fact per place. */

export const COUNTRY_FACTS: Record<string, string> = {
  AFG: "The Buddhas of Bamiyan were two giant cliff carvings—among the largest in the world before their destruction in 2001.",
  ALA: "Åland is an autonomous, Swedish-speaking archipelago that belongs to Finland but has its own parliament and flag.",
  ALB: "During the Cold War, Albania built hundreds of thousands of concrete bunkers—more per person than anywhere else on Earth.",
  DZA: "About 90% of Algeria is covered by the Sahara, yet most of its people live along the Mediterranean coast.",
  ASM: "American Samoa is the only U.S. territory south of the equator and is famous for its NFL players and tuna industry.",
  AND: "Andorra has no airport or railway—visitors arrive by road through mountain passes from France or Spain.",
  AGO: "Angola's Kalandula Falls are among the largest and most powerful waterfalls in Africa.",
  AIA: "Anguilla's beaches are so prized that the island has repeatedly voted against full independence to keep ties with Britain.",
  ATA: "Antarctica holds about 90% of the world's ice and roughly 70% of its fresh water.",
  ATG: "Antigua claims 365 beaches—one for every day of the year.",
  ARG: "Argentina's Perito Moreno Glacier is one of the few major glaciers in the world that is still advancing.",
  ARM: "Mount Ararat, visible from much of Armenia, is a national symbol though it lies just across the border in Türkiye.",
  ABW: "Aruba sits outside the Caribbean hurricane belt, giving it reliably sunny weather year-round.",
  AUS: "Australia is home to more venomous snakes than any other country—and most of its wildlife is found nowhere else.",
  AUT: "Vienna ranked among Europe's great imperial capitals; Mozart, Beethoven, and Strauss all made their mark here.",
  AZE: "Nearly half of Azerbaijan lies below sea level thanks to the Caspian shoreline and the low-lying Kura plain.",
  BHS: "The Bahamas has more than 700 islands and cays spread across clear turquoise shallows.",
  BHR: "Bahrain's Tree of Life is a lone mesquite tree thriving in the desert with no obvious water source for centuries.",
  BGD: "Bangladesh crams more than 170 million people into a delta the size of Iowa—one of the densest countries on Earth.",
  BRB: "Barbados is the easternmost island of the Caribbean and was once a major center of British sugar production.",
  BLR: "About 40% of Belarus is forested, earning it the nickname 'the lungs of Europe.'",
  BEL: "Belgium produces more than 1,500 varieties of beer and has been brewing for centuries.",
  BLZ: "Belize is home to the Great Blue Hole, a perfect circular sinkhole visible from space.",
  BEN: "Benin was once the powerful Kingdom of Dahomey, whose all-female warrior units inspired the Dora Milaje in Black Panther.",
  BMU: "Bermuda's pink-sand beaches get their color from crushed coral and shell fragments mixed with white sand.",
  BTN: "Bhutan measures progress with Gross National Happiness instead of focusing only on economic output.",
  BOL: "Bolivia has two capital cities: La Paz is the administrative seat and Sucre the constitutional capital.",
  BIH: "Mostar's Ottoman-era Stari Most bridge was destroyed in 1993 and painstakingly rebuilt stone by stone.",
  BWA: "Botswana's Okavango Delta is one of the world's largest inland deltas—a desert oasis teeming with wildlife.",
  BVT: "Bouvet Island is one of the most remote uninhabited islands on Earth, more than 1,000 miles from Antarctica.",
  BRA: "Brazil contains about 60% of the Amazon rainforest—the largest tropical forest on the planet.",
  IOT: "The Chagos Archipelago includes Diego Garcia, a strategically vital U.S.–U.K. military base in the Indian Ocean.",
  VGB: "The British Virgin Islands are a sailing paradise with dozens of sheltered bays and reef-protected waters.",
  BRN: "Brunei is one of the world's richest nations per capita, built largely on offshore oil and gas.",
  BGR: "Bulgaria is one of the world's oldest countries and still uses the Cyrillic alphabet invented by local saints.",
  BFA: "Burkina Faso means 'land of upright people' in Mossi and Dioula.",
  BDI: "Burundi and Rwanda were once a single kingdom before European colonization split them.",
  KHM: "Angkor Wat in Cambodia is the largest religious monument in the world by land area.",
  CMR: "Cameroon is nicknamed 'Africa in miniature' for its coast, rainforest, savanna, and volcanic highlands in one country.",
  CAN: "Canada has more lakes than the rest of the world's countries combined.",
  CPV: "Cape Verde's music—especially morna—has influenced styles across the Atlantic world.",
  BES: "Bonaire, Sint Eustatius, and Saba are Caribbean municipalities of the Netherlands known for diving and reefs.",
  CYM: "The Cayman Islands are a global financial hub with more registered companies than residents.",
  CAF: "The Central African Republic sits near the continent's geographic center, largely covered in rainforest.",
  TCD: "Lake Chad, which Chad is named for, has shrunk dramatically since the 1960s—an environmental crisis for the region.",
  CHL: "Chile is more than 4,000 km long but averages only about 177 km wide—one of the world's most stretched countries.",
  CHN: "China's Great Wall isn't one continuous wall—it's a network of fortifications built over many centuries.",
  CXR: "Christmas Island is famous for the annual red crab migration, when millions of crabs cross roads and beaches.",
  CCK: "The Cocos (Keeling) Islands are a remote coral atoll group in the Indian Ocean with a population under 600.",
  COL: "Colombia produces more emeralds than any other country and is one of the world's top coffee exporters.",
  COM: "Comoros is one of the world's largest producers of ylang-ylang, a flower essential to many perfumes.",
  COG: "The Congo Basin rainforest is the world's second-largest tropical forest after the Amazon.",
  COK: "Cook Islanders carry New Zealand passports but govern themselves in free association with Wellington.",
  CRI: "Costa Rica abolished its army in 1948 and redirected military spending to education and health care.",
  HRV: "Dubrovnik's medieval walls in Croatia became a filming location for King's Landing in Game of Thrones.",
  CUB: "Cuba's classic 1950s American cars are still on the road thanks to decades of ingenious local repair.",
  CUW: "Curaçao's Handelskade waterfront is lined with pastel Dutch colonial buildings overlooking the harbor.",
  CYP: "Cyprus is said to be the birthplace of Aphrodite, the Greek goddess of love.",
  CZE: "Prague's Astronomical Clock in Czechia has been keeping time since 1410—one of the oldest still working.",
  DNK: "Denmark's LEGO bricks were invented in Billund, where the original LEGOLAND theme park still stands.",
  DJI: "Djibouti sits on the Afar Triple Junction where three tectonic plates pull apart—creating dramatic rift landscapes.",
  DMA: "Dominica's Boiling Lake is the world's second-largest hot spring and steams like a giant cauldron.",
  DOM: "The Dominican Republic shares Hispaniola with Haiti—the only island split between two nations in the Caribbean.",
  COD: "The Congo River is the world's deepest river and second-largest by discharge, cutting through DR Congo's rainforests.",
  ECU: "Ecuador is named for the equator, which runs through the country—and the Galápagos Islands belong to it.",
  EGY: "The Great Pyramid of Giza was the tallest human-made structure in the world for nearly 4,000 years.",
  SLV: "El Salvador is the smallest and most densely populated country in Central America.",
  GNQ: "Equatorial Guinea is the only African country with Spanish as an official language.",
  ERI: "Eritrea's capital Asmara has one of the world's finest collections of Art Deco and Modernist architecture.",
  EST: "Estonia is one of the world's most digital societies—citizens can vote, sign documents, and file taxes online.",
  SWZ: "Eswatini (formerly Swaziland) is one of the world's last absolute monarchies in Africa.",
  ETH: "Ethiopia follows its own calendar—about seven to eight years behind the Gregorian calendar most of the world uses.",
  FLK: "The Falkland Islands were the setting of a brief but intense war between Britain and Argentina in 1982.",
  FRO: "Faroe Islanders drive through tunnels between islands and generate much of their power from wind and hydro.",
  FJI: "Fiji straddles the International Date Line, so it is among the first countries to greet each new day.",
  FIN: "Finland has more saunas than cars—roughly one sauna for every two people.",
  FRA: "France is the most visited country on Earth, drawing more international tourists than any other nation.",
  GUF: "French Guiana hosts Europe's main spaceport at Kourou—rockets launch from South America but under French flag.",
  PYF: "French Polynesia's Bora Bora and Tahiti helped define the world's image of a tropical paradise.",
  ATF: "The French Southern Territories include remote sub-Antarctic islands with no permanent human population.",
  GAB: "Gabon preserves about 11% of its land in national parks—among the highest proportions in the world.",
  GMB: "The Gambia is a narrow strip of land along the Gambia River, surrounded on three sides by Senegal.",
  GEO: "Georgia claims to be the birthplace of wine—archaeologists found 8,000-year-old winemaking evidence here.",
  DEU: "Germany's Autobahn famously has long stretches with no official speed limit for cars.",
  GHA: "Ghana was the first sub-Saharan African country to gain independence from colonial rule, in 1957.",
  GIB: "The Rock of Gibraltar is a limestone promontory guarded by wild Barbary macaques—the only wild monkeys in Europe.",
  GRC: "Greece has thousands of islands, though only a few hundred are inhabited.",
  GRL: "Greenland is the world's largest island and is covered by an ice sheet up to three kilometers thick.",
  GRD: "Grenada is known as the 'Spice Isle' for its nutmeg, mace, and cinnamon exports.",
  GLP: "Guadeloupe's La Soufrière volcano last erupted in 1976, forcing the evacuation of 73,000 people.",
  GUM: "Guam is the westernmost U.S. territory and a key military hub in the Pacific.",
  GTM: "Guatemala's Tikal ruins were a major Maya city—its temples rise above the Petén jungle canopy.",
  GGY: "Guernsey cows, famous worldwide for rich milk, take their name from this Channel Island.",
  GIN: "Guinea holds about one-third of the world's bauxite—the ore used to make aluminum.",
  GNB: "Guinea-Bissau's Bijagós Archipelago is a UNESCO biosphere reserve of mangroves and rare sea turtles.",
  GUY: "About 80% of Guyana is covered by pristine Amazon rainforest—one of the highest percentages in South America.",
  HTI: "Haiti was the first nation founded by formerly enslaved people who won independence, in 1804.",
  HMD: "Heard Island and McDonald Islands are among the most remote places on Earth, near Antarctica.",
  HND: "Honduras's Copán ruins feature some of the finest Maya stone carving in Central America.",
  HKG: "Hong Kong has more skyscrapers than any other city in the world—well over 500 buildings above 150 meters.",
  HUN: "Hungary's capital Budapest was formed by merging three cities and sits atop more than 100 thermal springs.",
  ISL: "Iceland runs almost entirely on renewable energy and sits atop the Mid-Atlantic Ridge, splitting two continents.",
  IND: "India has 22 official languages and is on track to become the world's most populous country.",
  IDN: "Indonesia is the world's largest archipelago—more than 17,000 islands spanning three time zones.",
  IRN: "Persian carpets from Iran are so prized that fine antique rugs can sell for millions of dollars.",
  IRQ: "Mesopotamia—'the land between the rivers'—in modern Iraq is where writing, the wheel, and cities first emerged.",
  IRL: "Ireland is called the Emerald Isle for its lush green countryside shaped by Gulf Stream rains.",
  IMN: "The Isle of Man is a self-governing Crown dependency famous for the TT motorcycle races since 1907.",
  ISR: "The Dead Sea shoreline in Israel is the lowest dry land on Earth—about 430 meters below sea level.",
  ITA: "Italy has more UNESCO World Heritage Sites than any other country—58 and counting.",
  CIV: "Ivory Coast produces about 40% of the world's cocoa, making it the top chocolate ingredient supplier.",
  JAM: "Jamaica gave the world reggae—Bob Marley's music turned a small island sound into a global movement.",
  JPN: "Japan has more than 6,800 islands and sits on the Pacific Ring of Fire with over 100 active volcanoes.",
  JEY: "Jersey's tidal range is among the largest in the world—at low tide, the island nearly doubles in size.",
  JOR: "Petra in Jordan is a rose-red city carved into sandstone cliffs by the Nabataeans over 2,000 years ago.",
  KAZ: "Kazakhstan is the world's largest landlocked country and was the last Soviet republic to declare independence.",
  KEN: "Kenya's Great Rift Valley lakes draw millions of flamingos, turning shores pink during migration.",
  KIR: "Kiribati is one of the first countries likely to lose land to rising seas—some islands sit just two meters above water.",
  UNK: "Kosovo declared independence in 2008; its flag shows a map of the country with six stars for its main ethnic groups.",
  KWT: "Kuwait's Liberation Tower was named after the 1991 Gulf War that ended the Iraqi occupation.",
  KGZ: "Kyrgyzstan is over 90% mountainous—the Tian Shan range dominates the landscape.",
  LAO: "Laos is the most heavily bombed country per capita in history due to the Secret War during the Vietnam era.",
  LVA: "Riga, Latvia's capital, has one of Europe's largest collections of Art Nouveau architecture.",
  LBN: "Lebanon's cedars appear on its flag and were prized by ancient Egyptians and Phoenicians for shipbuilding.",
  LSO: "Lesotho is entirely surrounded by South Africa and is the only country in the world that lies entirely above 1,000 meters.",
  LBR: "Liberia was founded in the 19th century by freed American slaves—its flag echoes the U.S. stars and stripes.",
  LBY: "Much of Libya lies within the Sahara, including the ancient Roman ruins of Leptis Magna on the coast.",
  LIE: "Liechtenstein is one of only two doubly landlocked countries—surrounded by landlocked nations.",
  LTU: "Lithuania was the last European nation to abandon paganism and the first Soviet republic to declare independence.",
  LUX: "Luxembourg has the highest GDP per capita in the world and is a founding member of the European Union.",
  MAC: "Macau was a Portuguese colony for 400 years before returning to China in 1999—it rivals Las Vegas for gambling revenue.",
  MDG: "Madagascar broke away from Africa 88 million years ago—about 90% of its wildlife is found nowhere else.",
  MWI: "Lake Malawi contains more species of fish than any other lake on Earth—hundreds of colorful cichlids.",
  MYS: "Malaysia's Petronas Towers in Kuala Lumpur were the world's tallest buildings from 1998 to 2004.",
  MDV: "The Maldives is the world's lowest country—its highest natural point is only about 2.4 meters above sea level.",
  MLI: "Timbuktu in Mali was once a legendary center of Islamic learning and trans-Saharan trade.",
  MLT: "Malta's Megalithic Temples are older than Stonehenge and the Egyptian pyramids.",
  MHL: "The Marshall Islands include Bikini Atoll, where U.S. nuclear tests in the 1940s–50s forced entire communities to relocate.",
  MTQ: "Martinique's Mount Pelée erupted in 1902, destroying the city of Saint-Pierre in minutes.",
  MRT: "Mauritania's Richat Structure—a giant bull's-eye in the Sahara—is visible from space and was once thought to be an impact crater.",
  MUS: "Mauritius was the only known home of the dodo before the flightless bird was hunted to extinction by the 1680s.",
  MYT: "Mayotte sits in the Comoros archipelago but chose to remain French—a source of ongoing regional tension.",
  MEX: "Mexico City was built on the ruins of Tenochtitlán, the Aztec capital that once floated on a lake.",
  FSM: "Micronesia spans more than 2.7 million square kilometers of ocean but has a land area smaller than Rhode Island.",
  MDA: "Moldova's Mileștii Mici holds one of the world's largest wine cellars—over 200 km of underground tunnels.",
  MCO: "Monaco is smaller than Central Park in New York yet packs luxury casinos, a Grand Prix, and a royal palace.",
  MNG: "Genghis Khan's empire began on the Mongolian steppe—the country still celebrates him as a founding father.",
  MNE: "Montenegro means 'Black Mountain' in Venetian Italian, named for the dark forests on Mount Lovćen.",
  MSR: "Montserrat's Soufrière Hills volcano erupted in 1995, burying the capital Plymouth in ash and forcing evacuation.",
  MAR: "Morocco's Chefchaouen is famous for its buildings painted in shades of blue.",
  MOZ: "Mozambique's Bazaruto Archipelago protects dugongs—rare sea cows once mistaken for mermaids by sailors.",
  MMR: "Myanmar's Shwedagon Pagoda in Yangon is covered in gold leaf and topped with thousands of diamonds and rubies.",
  NAM: "Namibia's Namib Desert is considered the world's oldest desert—some dunes are millions of years old.",
  NRU: "Nauru was once among the richest countries per capita thanks to phosphate mining—but the deposits are nearly gone.",
  NPL: "Mount Everest's summit sits on the Nepal–China border—the world's highest point at 8,849 meters.",
  NLD: "About a quarter of the Netherlands lies below sea level, protected by an elaborate system of dikes and pumps.",
  NCL: "New Caledonia has the world's largest lagoon, surrounded by the world's second-longest barrier reef.",
  NZL: "New Zealand was the first country to give women the right to vote, in 1893.",
  NIC: "Nicaragua has the two largest freshwater lakes in Central America—Lake Nicaragua even has freshwater sharks.",
  NER: "The Sahara covers most of Niger, yet the country takes its name from the Niger River that arcs through its southwest.",
  NGA: "Nigeria has Africa's largest population and Nollywood produces more films than Hollywood by volume.",
  NIU: "Niue is one of the world's largest raised coral atolls and uses New Zealand currency.",
  NFK: "Norfolk Island was settled by descendants of the Bounty mutineers after they left Pitcairn.",
  PRK: "North Korea and South Korea are still technically at war—the 1953 armistice never became a peace treaty.",
  MKD: "North Macedonia's Lake Ohrid is one of Europe's oldest and deepest lakes, home to species found nowhere else.",
  MNP: "The Mariana Trench near the Northern Mariana Islands is the deepest point in the ocean—almost 11 km down.",
  NOR: "Norway's fjords were carved by Ice Age glaciers and its coastline would stretch halfway around the equator if straightened.",
  OMN: "Oman's Sultan Qaboos transformed the country from an isolated sultanate into a modern nation over his 50-year reign.",
  PAK: "Pakistan is home to K2, the world's second-highest mountain—harder to climb than Everest and nicknamed the Savage Mountain.",
  PLW: "Palau's Jellyfish Lake lets swimmers snorkel among millions of harmless golden jellyfish.",
  PSE: "Jericho in the Palestinian territories is one of the oldest continuously inhabited cities in the world.",
  PAN: "The Panama Canal saves ships a 13,000-km journey around South America by cutting through the isthmus.",
  PNG: "Papua New Guinea has more than 800 living languages—more than any other country.",
  PRY: "Paraguay's Guaraní language is one of the few indigenous American languages with official status alongside Spanish.",
  PER: "Machu Picchu in Peru is a 15th-century Inca citadel perched 2,430 meters above sea level in the Andes.",
  PHL: "The Philippines consists of about 7,641 islands and is the world's top exporter of nurses.",
  PCN: "Pitcairn Island was settled by mutineers from HMS Bounty—today fewer than 50 people live there.",
  POL: "Poland's Wieliczka Salt Mine has chapels, sculptures, and chandeliers carved entirely from salt.",
  PRT: "Portugal's explorers opened sea routes to India, Brazil, and Japan—shaping the first global age of trade.",
  PRI: "Puerto Rico's bioluminescent bays glow blue at night when microscopic organisms are disturbed in the water.",
  QAT: "Qatar will have hosted a FIFA World Cup where every stadium was within about an hour's drive of each other.",
  REU: "Réunion's Piton de la Fournaise is one of the world's most active volcanoes, erupting dozens of times since 2000.",
  ROU: "Romania's Transylvania region inspired Bram Stoker's Dracula—though Vlad the Impaler never lived in Bran Castle.",
  RUS: "Russia spans 11 time zones and crosses both Europe and Asia—it is the largest country on Earth by area.",
  RWA: "Rwanda banned plastic bags nationwide in 2008 and holds a monthly community cleanup called Umuganda.",
  BLM: "Saint Barthélemy is a glamorous Caribbean island nicknamed St. Barts, popular with yachts and celebrities.",
  SHN: "Saint Helena is where Napoleon was exiled after Waterloo—it took ships weeks to reach from Europe.",
  KNA: "Saint Kitts and Nevis is the smallest sovereign country in the Western Hemisphere by both area and population.",
  LCA: "Saint Lucia's twin Pitons—volcanic spires rising from the sea—are a UNESCO World Heritage Site.",
  MAF: "Saint Martin is split between France and the Netherlands—the smallest landmass shared by two nations.",
  SPM: "Saint Pierre and Miquelon are French islands off Canada's coast—residents use the euro just 25 km from Newfoundland.",
  VCT: "Saint Vincent's La Soufrière volcano erupted in 2021, covering much of the island in ash.",
  WSM: "Samoa skipped December 30, 2011 entirely when it moved across the International Date Line to align with trading partners.",
  SMR: "San Marino claims to be the world's oldest republic, founded in 301 AD on Mount Titano.",
  STP: "São Tomé and Príncipe's cocoa plantations once made it a major chocolate supplier to Europe.",
  SAU: "Saudi Arabia has no permanent rivers—the country is mostly desert, including the vast Empty Quarter.",
  SEN: "Senegal's Lake Retba is bright pink from salt-loving algae and is harvested for salt like the Dead Sea.",
  SRB: "Serbia sits at a crossroads of empires—Belgrade is one of Europe's oldest continuously inhabited cities.",
  SYC: "Seychelles's Vallée de Mai preserves the coco de mer, a palm that produces the world's heaviest seed.",
  SLE: "Sierra Leone's name means 'lion mountains' in Portuguese, though lions no longer live there.",
  SGP: "Singapore transformed from a fishing village to a global financial hub in a single generation.",
  SXM: "Sint Maarten's Maho Beach is famous for airliners passing just meters overhead on approach to the runway.",
  SVK: "Slovakia has more castles and châteaux per capita than almost any other country in Europe.",
  SVN: "Slovenia's Postojna Cave holds a unique species of blind salamander called the olm—or 'human fish.'",
  SLB: "Solomon Islanders fought alongside U.S. Marines in World War II's brutal Guadalcanal campaign.",
  SOM: "Somalia has the longest coastline on mainland Africa but has struggled with piracy off its shores.",
  ZAF: "South Africa has three capital cities—each hosts a different branch of government.",
  SGS: "South Georgia's Grytviken whaling station is where explorer Ernest Shackleton is buried.",
  KOR: "South Korea's Hangul alphabet was scientifically designed in 1443 so anyone could learn to read.",
  SSD: "South Sudan is the world's newest widely recognized country, gaining independence from Sudan in 2011.",
  ESP: "Spain's Sagrada Família in Barcelona has been under construction since 1882 and is still not finished.",
  LKA: "Sri Lanka was once called Ceylon and produces Ceylon tea from highland plantations.",
  SDN: "Sudan has more pyramids than Egypt—ancient Nubian kingdoms left hundreds along the Nile.",
  SUR: "Suriname is the smallest independent country in South America and one of the most forested.",
  SJM: "Svalbard's Global Seed Vault stores backup copies of crop seeds from around the world in Arctic permafrost.",
  SWE: "Sweden's Nobel Prizes are awarded each year in Stockholm—except Peace, which is given in Oslo.",
  CHE: "Switzerland has four official languages and has not fought a foreign war since 1815.",
  SYR: "Damascus in Syria is one of the oldest continuously inhabited cities in the world.",
  TWN: "Taiwan's Taipei 101 was the world's tallest building from 2004 to 2010 and is designed to withstand typhoons and earthquakes.",
  TJK: "Tajikistan is over 90% mountainous—the Pamir range is nicknamed the 'Roof of the World.'",
  TZA: "Tanzania's Serengeti hosts the largest terrestrial mammal migration on Earth—over a million wildebeest.",
  THA: "Thailand is the only Southeast Asian country never colonized by a European power.",
  TLS: "Timor-Leste is one of the world's youngest countries, gaining full independence in 2002 after centuries of occupation.",
  TGO: "Togo is one of the world's top producers of phosphates, used in fertilizer.",
  TKL: "Tokelau is one of the first territories to produce more than 100% of its electricity from solar power.",
  TON: "Tonga is the only Pacific nation that was never fully colonized—it became a constitutional monarchy in 1875.",
  TTO: "Trinidad and Tobago invented the steelpan—the only acoustic instrument invented in the 20th century.",
  TUN: "Tunisia's ancient city of Carthage once rivaled Rome before being destroyed and rebuilt by the Romans.",
  TUR: "Istanbul in Türkiye is the only major city spanning two continents—Europe and Asia.",
  TKM: "Turkmenistan's Darvaza gas crater has burned continuously in the desert since Soviet engineers lit it in 1971.",
  TCA: "Turks and Caicos has some of the clearest turquoise water in the Caribbean and a thriving conch fishery.",
  TUV: "Tuvalu is among the world's smallest and most low-lying countries—rising seas threaten its very existence.",
  UGA: "Uganda is one of the few places where you can see mountain gorillas in the wild—about half the world's population lives here.",
  UKR: "Ukraine is one of the world's largest grain exporters—the 'breadbasket of Europe.'",
  ARE: "Dubai in the UAE built the world's tallest building, the Burj Khalifa, at 828 meters.",
  GBR: "The United Kingdom is made up of four countries—England, Scotland, Wales, and Northern Ireland.",
  USA: "The United States has the world's largest economy and is the third most populous country.",
  UMI: "The U.S. Minor Outlying Islands include Midway Atoll, site of a pivotal 1942 naval battle in World War II.",
  VIR: "The U.S. Virgin Islands were purchased from Denmark in 1917 for $25 million in gold.",
  URY: "Uruguay was the first country to legalize recreational cannabis nationwide, in 2013.",
  UZB: "Uzbekistan's Registan in Samarkand was a glittering center of the Silk Road trade route.",
  VUT: "Vanuatu invented bungee jumping—local land divers on Pentecost Island inspired the modern sport.",
  VAT: "Vatican City is the world's smallest independent state—about 44 hectares enclosed within Rome.",
  VEN: "Venezuela's Angel Falls is the world's highest uninterrupted waterfall, plunging 979 meters.",
  VNM: "Vietnam's Ha Long Bay has thousands of limestone karsts rising from emerald water—a UNESCO World Heritage Site.",
  WLF: "Wallis and Futuna is one of the last French territories where traditional kings still hold official authority.",
  ESH: "Western Sahara is one of the most sparsely populated places on Earth—mostly desert with a disputed political status.",
  YEM: "Yemen's Old City of Sana'a has distinctive multi-story tower houses decorated with white gypsum patterns.",
  ZMB: "Zambia's Victoria Falls—locally called Mosi-oa-Tunya, 'the smoke that thunders'—is one of the world's largest waterfalls.",
  ZWE: "Zimbabwe's Great Zimbabwe ruins were the capital of a medieval trading empire that exported gold to the Indian Ocean.",
};

export const STATE_FACTS: Record<string, string> = {
  "US-AL": "The Saturn V rockets that carried Apollo astronauts to the Moon were designed and built in Huntsville.",
  "US-AK": "Alaska is the northernmost, westernmost, and easternmost U.S. state—the Aleutian Islands cross the 180th meridian into the Eastern Hemisphere.",
  "US-AZ": "The Grand Canyon exposes nearly two billion years of geology in its colorful layered walls.",
  "US-AR": "Hot Springs National Park in Arkansas predates Yellowstone and was the first U.S. federal reserve.",
  "US-CA": "California's economy is larger than that of most countries—if it were independent, it would rank among the world's biggest.",
  "US-CO": "Denver sits exactly one mile above sea level, giving Colorado its 'Mile High City' nickname.",
  "US-CT": "The Fundamental Orders of Connecticut, adopted in 1639, are often called the first written constitution in the Americas.",
  "US-DE": "Delaware was the first state to ratify the U.S. Constitution on December 7, 1787.",
  "US-FL": "Florida has more coastline than any U.S. state except Alaska and is the only state bordering both the Atlantic and Gulf.",
  "US-GA": "Coca-Cola was invented by a pharmacist in Atlanta in 1886 and first sold at a local drugstore.",
  "US-HI": "Hawaii is the only U.S. state that grows coffee commercially and sits 2,400 miles from the mainland.",
  "US-ID": "Idaho produces about one-third of all potatoes grown in the United States.",
  "US-IL": "Chicago reversed the flow of its river in 1900 so wastewater would drain away from Lake Michigan.",
  "US-IN": "The Indianapolis 500, first held in 1911, is one of the oldest and most famous car races in the world.",
  "US-IA": "Iowa leads the nation in corn production and raises more pigs than any other state.",
  "US-KS": "The geographic center of the contiguous United States lies near Lebanon, Kansas.",
  "US-KY": "Kentucky produces about 95% of the world's bourbon and has more barrels of aging whiskey than people.",
  "US-LA": "New Orleans sits largely below sea level and relies on levees, pumps, and Mississippi River silt to stay dry.",
  "US-ME": "Maine supplies roughly 90% of the United States' lobster catch.",
  "US-MD": "The Star-Spangled Banner was written during the 1814 Battle of Baltimore at Fort McHenry.",
  "US-MA": "The first subway system in the Americas opened in Boston in 1897.",
  "US-MI": "Michigan touches four of the five Great Lakes and has more freshwater shoreline than any other state.",
  "US-MN": "Minnesota has more than 11,000 lakes and is the birthplace of water skiing and the Mall of America.",
  "US-MS": "The Mississippi River forms most of the state's western border and gave the state its name.",
  "US-MO": "The Gateway Arch in St. Louis is 630 feet tall—the tallest monument in the United States.",
  "US-MT": "Montana's name comes from the Spanish word montaña, though it is not the most mountainous U.S. state.",
  "US-NE": "Carhenge in Alliance is a full-scale replica of England's Stonehenge built from vintage American cars.",
  "US-NV": "About three-quarters of Nevada's population lives in the Las Vegas metro area.",
  "US-NH": "New Hampshire's license plates carry the bold motto 'Live Free or Die.'",
  "US-NJ": "Thomas Edison developed the practical light bulb, phonograph, and motion picture in his Menlo Park laboratory.",
  "US-NM": "Roswell became synonymous with UFO lore after a 1947 incident that still fuels conspiracy theories.",
  "US-NY": "More people live in New York City than in all but a handful of U.S. states.",
  "US-NC": "The Wright brothers achieved the first powered airplane flight at Kitty Hawk in 1903.",
  "US-ND": "Theodore Roosevelt National Park preserves the badlands where the future president ranched and found inspiration.",
  "US-OH": "Seven U.S. presidents were born in Ohio—more than any state except Virginia.",
  "US-OK": "Oklahoma City lies close to the geographic center of the contiguous United States.",
  "US-OR": "Crater Lake is the deepest lake in the United States, formed when a volcano collapsed about 7,700 years ago.",
  "US-PA": "Independence Hall in Philadelphia is where the Declaration of Independence and U.S. Constitution were signed.",
  "US-RI": "Rhode Island is the smallest U.S. state but has over 400 miles of coastline.",
  "US-SC": "The first shots of the Civil War were fired at Fort Sumter in Charleston Harbor in 1861.",
  "US-SD": "Mount Rushmore's 60-foot presidential faces were carved into the Black Hills over 14 years.",
  "US-TN": "Memphis is a cradle of blues and rock and roll—Elvis Presley's Graceland draws visitors from around the world.",
  "US-TX": "Texas was an independent republic for nearly ten years before joining the United States in 1845.",
  "US-UT": "The Great Salt Lake is saltier than the ocean, so swimmers float effortlessly on its surface.",
  "US-VT": "Ben & Jerry's ice cream began in a renovated gas station in Burlington in 1978.",
  "US-VA": "Eight U.S. presidents were born in Virginia—more than any other state.",
  "US-WA": "Mount Rainier is an active volcano towering over Seattle and visible across much of the Puget Sound.",
  "US-WV": "West Virginia split from Virginia during the Civil War and joined the Union as its own state in 1863.",
  "US-WI": "Wisconsin produces more cheese than any other U.S. state and hosts the Green Bay Packers' Lambeau Field.",
  "US-WY": "Yellowstone National Park—mostly in Wyoming—was the world's first national park, established in 1872.",
};

export function getCountryFact(code3: string): string | undefined {
  return COUNTRY_FACTS[code3.toUpperCase()];
}

export function getStateFact(code: string): string | undefined {
  return STATE_FACTS[code.toUpperCase()];
}
